### ISSUE TITLE
Issue with NASAaccess Package

### ISSUE THREAD

**Issue by kiema97** [nasa/NASAaccess#8]
I am running the following code in R:
`dem_path <- system.file("extdata",
                        "DEM_TX.tif",
                        package = "NASAaccess")`

`shape_path <- system.file("extdata",
                          "basin.shp",
                          packa`ge = "NASAaccess")`

`NASAaccess::GLDASwat(Dir = "./GLDASwat/",
         watershed = shape_path,
         DEM = dem_path,
         start = "2022-08-1",
         end = "2022-08-3")`

However, I encountered the following error:

`Error in R_nc4_open: NetCDF: Unknown file format
Error in ncdf4::nc_open(paste("./temp/", filenames[1], sep = "")) :
  Error in nc_open trying to open file ./temp/GLDAS_NOAH025_3H.A20220801.0000.021.nc4 (return_on_error= FALSE )`

I have checked my inputs and attempted various troubleshooting steps, but the issue persists. **I would appreciate your guidance on resolving this problem or any suggestions you might have. Your assistance is highly valuable to me.**

Thank you for your time and support.

**Comment by imohamme** [comment]
Hello @kiema97, Thanks for testing NASAaccess. One possible reason for the error you encountered is a corrupt file. This happens when the file is not fully downloaded to your machine `./temp`. When I tested your example, I found the GLDAS_NOAH025_3H.A20220801.0000.021.nc4 file size is 19.1 MB. Double check your file size and rerun the `GLDASwat` command again. If it is not around 19 MB I suggest to check your internet connection or change your timeout settings. Please see [how-do-i-set-a-timeout-for-utilsdownload-file-in-r](https://stackoverflow.com/questions/35282928/how-do-i-set-a-timeout-for-utilsdownload-file-in-r) for further details.
